services:
  - type: web_service
    name: online-backend
    env: node
    plan: free
    buildCommand: cd Frontend && npm install && VITE_API_URL=/api npm run build && cd ../Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET
      - key: ALLOWED_ORIGIN

  - type: static_site
    name: online-frontend
    env: static
    plan: free
    buildCommand: cd Frontend && npm install && npm run build
    publishPath: Frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://av-2-ls9k.onrender.com/api
